`torch.nn` is PyTorch’s high‑level neural‑network library. It provides the **Module** base class plus ready‑made layers, activation functions, loss functions, and helper utilities used to build and train models. [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html)

## What torch.nn does

- Defines `nn.Module`, the base class that tracks parameters, submodules, buffers and implements the `forward` method for all neural‑network components. [docs.pytorch](https://docs.pytorch.org/docs/stable/generated/torch.nn.Module.html)
- Provides standard building blocks: linear and convolution layers, RNNs, normalisation, dropout, embedding layers and more. [apxml](https://apxml.com/courses/getting-started-with-pytorch/chapter-4-building-models-torch-nn/common-layers-linear-convolutional-recurrent)
- Includes many loss (criterion) classes for regression, classification, and other tasks under `torch.nn`. [neptune](https://neptune.ai/blog/pytorch-loss-functions)
- Integrates tightly with autograd and optim, so `model.parameters()` can be passed directly to optimizers. [plus2net](https://www.plus2net.com/python/pytorch-nn-module.php)

In practice, you subclass `nn.Module`, define layers in `__init__`, wire them together in `forward`, then train with a loss from `nn` and an optimizer from `torch.optim`. [apxml](https://apxml.com/courses/getting-started-with-pytorch/chapter-4-building-models-torch-nn/torch-nn-module-base-class)

## Common layers in torch.nn

| Category | Class (nn.*) | Description |
|---|---|---|
| Linear | `Linear` | Fully connected affine layer; applies \(y = xA^T + b\).  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Convolution | `Conv1d`, `Conv2d`, `Conv3d` | Learnable convolution kernels over 1D/2D/3D inputs (time series, images, volumes).  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Transposed Conv | `ConvTranspose1d`, `ConvTranspose2d`, `ConvTranspose3d` | “Deconvolution”/upsampling convolutions, often in decoders and GANs.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Recurrent | `RNN`, `LSTM`, `GRU` | Recurrent layers for sequence data; LSTM/GRU mitigate vanishing gradients.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Embedding | `Embedding`, `EmbeddingBag` | Maps integer indices to dense vectors (e.g., word embeddings).  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Pooling | `MaxPool1d/2d/3d`, `AvgPool1d/2d/3d`, `Adaptive*Pool*` | Downsamples feature maps, taking max or average over windows.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Normalization | `BatchNorm1d/2d/3d` | Normalizes activations per batch to stabilize training.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| | `LayerNorm`, `InstanceNorm*`, `GroupNorm` | Alternative normalization schemes for sequences, style transfer, etc.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Dropout | `Dropout`, `Dropout2d`, `Dropout3d`, `AlphaDropout` | Randomly zeroes activations during training to reduce overfitting.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Padding | `ReflectionPad*`, `ReplicationPad*`, `ZeroPad2d`, `ConstantPad*` | Adds padding around inputs in different ways.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Upsampling | `Upsample`, `UpsamplingNearest2d`, `UpsamplingBilinear2d` | Increases spatial resolution via interpolation.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Sparse / others | `Identity`, `Flatten`, `Unflatten`, `UpsamplingBilinear2d` | Utility structural layers to reshape or pass data through.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |

## Activation functions in torch.nn

Available as modules (`nn.ReLU()`) and also as functions under `torch.nn.functional`. [codecademy](https://www.codecademy.com/resources/docs/pytorch/nn)

| Activation | Class (nn.*) | Description |
|---|---|---|
| ReLU | `ReLU`, `ReLU6` | Zeroes negative values; `ReLU6` clamps to  [dragon.seetatech](https://dragon.seetatech.com/api/python/torch/dtype).  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Leaky ReLU | `LeakyReLU` | Like ReLU but with small slope for negatives to avoid dead neurons.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| PReLU | `PReLU` | Parametric ReLU; negative slope is learned.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| ELU/SELU | `ELU`, `SELU` | Smooth activations with negative saturation; SELU used with self‑normalizing nets.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| GELU | `GELU` | Smooth, probabilistic variant of ReLU used in Transformers.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Sigmoid | `Sigmoid` | Maps to (0, 1); common in binary outputs.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Tanh | `Tanh` | Maps to (−1, 1); often used in RNNs.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Softmax | `Softmax`, `LogSoftmax` | Converts logits to probabilities (or log‑probabilities) over classes.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Softplus / Softsign | `Softplus`, `Softsign` | Smooth approximations used in some architectures.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Others | `Softmin`, `Softshrink`, `Hardtanh`, `SiLU` (Swish) | Additional activations for specialized use‑cases.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |

## Loss (criterion) functions in torch.nn

All standard loss functions live in `torch.nn` and are used as `criterion = nn.XxxLoss()`. [geeksforgeeks](https://www.geeksforgeeks.org/deep-learning/pytorch-loss-functions/)

| Task type | Class (nn.*) | Description |
|---|---|---|
| Regression | `MSELoss` | Mean squared error between predictions and targets.  [geeksforgeeks](https://www.geeksforgeeks.org/deep-learning/pytorch-loss-functions/) |
| | `L1Loss` | Mean absolute error (L1) loss.  [neptune](https://neptune.ai/blog/pytorch-loss-functions) |
| | `SmoothL1Loss`, `HuberLoss` | Robust combination of L1 and L2 behavior.  [geeksforgeeks](https://www.geeksforgeeks.org/deep-learning/pytorch-loss-functions/) |
| Binary classification | `BCELoss` | Binary cross‑entropy; expects probabilities (after sigmoid).  [geeksforgeeks](https://www.geeksforgeeks.org/deep-learning/pytorch-loss-functions/) |
| | `BCEWithLogitsLoss` | BCE with internal sigmoid + numerical stabilization.  [geeksforgeeks](https://www.geeksforgeeks.org/deep-learning/pytorch-loss-functions/) |
| Multi‑class classification | `CrossEntropyLoss` | Combines `LogSoftmax` and `NLLLoss` for integer class targets.  [geeksforgeeks](https://www.geeksforgeeks.org/deep-learning/pytorch-loss-functions/) |
| | `NLLLoss` | Negative log‑likelihood; used with external `LogSoftmax`.  [geeksforgeeks](https://www.geeksforgeeks.org/deep-learning/pytorch-loss-functions/) |
| Multi‑label / others | `MultiLabelSoftMarginLoss`, `MultiMarginLoss` | For multi‑label tasks and margin‑based classification.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Probabilistic | `KLDivLoss` | Kullback–Leibler divergence between distributions.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Embedding / metric | `CosineEmbeddingLoss`, `TripletMarginLoss`, `MarginRankingLoss` | For similarity learning and ranking tasks.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| Segmentation | `CrossEntropyLoss` (on per‑pixel logits) | Standard choice for semantic segmentation outputs.  [geeksforgeeks](https://www.geeksforgeeks.org/deep-learning/pytorch-loss-functions/) |

## Other important utilities in torch.nn

| Utility | What it does |
|---|---|
| `nn.Module` | Base class for all layers and models; manages parameters, buffers, submodules and `forward`.  [docs.pytorch](https://docs.pytorch.org/docs/stable/generated/torch.nn.Module.html) |
| `nn.Sequential` | Container that chains modules in order; forward = apply them in sequence.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| `nn.ModuleList`, `nn.ModuleDict` | Containers to hold lists/dicts of submodules (e.g., dynamic architectures).  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| `nn.Parameter` | Marks a tensor as a learnable parameter to be returned by `model.parameters()`.  [docs.pytorch](https://docs.pytorch.org/docs/stable/generated/torch.nn.Module.html) |
| `nn.init` (submodule) | Functions to initialize weights (e.g., Xavier/He initialization).  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| `nn.utils.clip_grad_norm_`, `clip_grad_value_` | Gradient clipping helpers to stabilize training.  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| `nn.utils.rnn` | Utilities for variable‑length sequences (e.g., `pack_padded_sequence`).  [docs.pytorch](https://docs.pytorch.org/docs/stable/nn.html) |
| `module.train() / eval()` | Switches modules between training and evaluation modes (affects dropout, batchnorm, etc.).  [apxml](https://apxml.com/courses/getting-started-with-pytorch/chapter-4-building-models-torch-nn/torch-nn-module-base-class) |

In [ ]:
import torch
import torch.nn as nn

In [ ]:
# Creating a class to inherit nn.Module

class NeuralNetwork(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
## Creating a dataset
features = torch.randn(10,5)

# Creating a model object
model = NeuralNetwork(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4232],
        [0.6037],
        [0.6111],
        [0.2873],
        [0.6019],
        [0.7193],
        [0.5140],
        [0.7472],
        [0.6403],
        [0.7539]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1792, -0.4295, -0.0140, -0.4070,  0.1240]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.2462], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
NeuralNetwork                            [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# Creating other neural network with ReLU and Hidden Layer

# Creating a class to inherit nn.Module

class NeuralNetwork_ReLU(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
## Creating a dataset
features = torch.randn(10,5)

# Creating a model object
model = NeuralNetwork_ReLU(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.6124],
        [0.5821],
        [0.7183],
        [0.7361],
        [0.5940],
        [0.5815],
        [0.5790],
        [0.6435],
        [0.6436],
        [0.6045]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight, model.linear1.bias

(Parameter containing:
 tensor([[ 0.0519,  0.2404,  0.0103,  0.1521,  0.4337],
         [-0.1668, -0.1835, -0.1676,  0.3779,  0.3350],
         [ 0.2533, -0.0367,  0.4130, -0.3189, -0.3164]], requires_grad=True),
 Parameter containing:
 tensor([0.2434, 0.3297, 0.1426], requires_grad=True))

In [ ]:
model.linear2.weight, model.linear2.bias

(Parameter containing:
 tensor([[ 0.3499,  0.2940, -0.2629]], requires_grad=True),
 Parameter containing:
 tensor([0.5117], requires_grad=True))

In [ ]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
## Now creating Neural Network with Sequential Container

class SequentialNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )


  def forward(self, features):
    out = self.network(features)

    return out