In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available.")
  print(f"CUDA Device: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available, Running on CPU.")

GPU is not available, Running on CPU.


## Creating a Tensor

In [ ]:
# Using empty tensor
torch.empty(2,3)

tensor([[-5.0522e-19,  4.4236e-41, -5.0522e-19],
        [ 4.4236e-41,  0.0000e+00,  0.0000e+00]])

In [ ]:
# Check type
type(torch.empty(2,3))

torch.Tensor

In [ ]:
# Creating zero tensor
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Creating ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#random tensor
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [ ]:
#manual seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
#custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways of creating tensor

## using arange
print(f"using arange-> {torch.arange(1,10)}")

#using linespace
print(f"using linspace-> {torch.linspace(0,10,10)}")

#using eye
print(f"using eye-> {torch.eye(5)}")

# using full
print(f"using full-> {torch.full((3,3), 5)}")

using arange-> tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
tensor_x = torch.tensor([[1,2,3,4],[6,7,8,9]])

print(f"Shape of tensor_x is {tensor_x.shape}")

Shape of tensor_x is torch.Size([2, 4])


In [ ]:
# Creating tensor of shape 'tensor_x'

torch.empty_like(tensor_x)

tensor([[         194742,               0,       799447808, 135585624933680],
        [      799447808,           65280,              64,             256]])

In [ ]:
torch.zeros_like(tensor_x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
# torch.rand_like(tensor_x) ## will throw a Runtime Error

## Tensor Data Types

In [ ]:
# Find the data type of tensor_x

tensor_x.dtype

torch.int64

In [ ]:
## Assigning a new data type

torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
torch.tensor([1.45,2.87,3.01], dtype=torch.int64)

tensor([1, 2, 3])

In [ ]:
## Using 'to' function to change the data type of a function

tensor_x = tensor_x.to(torch.float64)

In [ ]:
# Now again running the above 'rand_like' function
torch.rand_like(tensor_x)

tensor([[0.0526, 0.5262, 0.4768, 0.9552],
        [0.9288, 0.0835, 0.1326, 0.1571]], dtype=torch.float64)

| Data type                     | Dtype                  | Description                                                                    |
| ----------------------------- | ---------------------- | ------------------------------------------------------------------------------ |
| 32-bit floating point         | torch.float32          | 32-bit floating point. pytorch​                                                |
| 64-bit floating point         | torch.float64          | 64-bit floating point. pytorch​                                                |
| 16-bit floating point         | torch.float16          | 16-bit floating point. pytorch​                                                |
| Brain floating point (16-bit) | torch.bfloat16         | 16-bit floating point, sometimes referred to as Brain floating point. pytorch​ |
| Complex (2×float16)           | torch.complex32        | 32-bit complex with two float16 components. pytorch​                           |
| Complex (2×float32)           | torch.complex64        | 64-bit complex with two float32 components. pytorch​                           |
| Complex (2×float64)           | torch.complex128       | 128-bit complex with two float64 components. pytorch​                          |
| Float8 (E4M3FN)               | torch.float8_e4m3fn    | 8-bit floating point, S-E-M 1-4-3. pytorch​                                    |
| Float8 (E5M2)                 | torch.float8_e5m2      | 8-bit floating point, S-E-M 1-5-2. pytorch​                                    |
| Float8 (E4M3FNUZ)             | torch.float8_e4m3fnuz  | 8-bit floating point, S-E-M 1-4-3. pytorch​                                    |
| Float8 (E5M2FNUZ)             | torch.float8_e5m2fnuz  | 8-bit floating point, S-E-M 1-5-2. pytorch​                                    |
| Float8 (E8M0FNU)              | torch.float8_e8m0fnuz  | 8-bit floating point, S-E-M 0-8-0. pytorch​                                    |
| Packed float4                 | torch.float4_e2m1fn_x2 | Packed 4-bit floating point, S-E-M 1-2-1. pytorch​                             |
| 8-bit unsigned integer        | torch.uint8            | 8-bit integer (unsigned). pytorch​                                             |
| 8-bit signed integer          | torch.int8             | 8-bit integer (signed). pytorch​                                               |
| 16-bit unsigned integer       | torch.uint16           | 16-bit integer (unsigned). pytorch​                                            |
| 16-bit signed integer         | torch.int16            | 16-bit integer (signed). pytorch​                                              |
| 32-bit unsigned integer       | torch.uint32           | 32-bit integer (unsigned). pytorch​                                            |
| 32-bit signed integer         | torch.int32            | 32-bit integer (signed). pytorch​                                              |
| 64-bit unsigned integer       | torch.uint64           | 64-bit integer (unsigned). pytorch​                                            |
| 64-bit signed integer         | torch.int64            | 64-bit integer (signed). pytorch​                                              |
| Boolean                       | torch.bool             | Boolean. pytorch​                                                              |
| Quantized unsigned 8-bit      | torch.quint8           | Quantized dtype supported by torch.quantize_per_tensor. pytorch​               |
| Quantized signed 8-bit        | torch.qint8            | Quantized dtype supported by torch.quantize_per_tensor. pytorch​               |
| Quantized signed 32-bit       | torch.qint32           | Quantized dtype supported by torch.quantize_per_tensor. pytorch​               |

## Mathematical Operation

#### 1. Scalar Operations

In [ ]:
# Creating a tensor
x = torch.rand(2,3)
x

tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])

In [ ]:
# addition
print(x + 2)

# substraction
print(x - 2)

# multiplication
print(x * 2)

# division
print(x / 3)

# int division
print((x * 100)//3)

# mod
print(((x * 100)//3)%2)

# power
print(x ** 2)

tensor([[2.2969, 2.8317, 2.1053],
        [2.2695, 2.3588, 2.1994]])
tensor([[-1.7031, -1.1683, -1.8947],
        [-1.7305, -1.6412, -1.8006]])
tensor([[0.5938, 1.6634, 0.2106],
        [0.5390, 0.7176, 0.3987]])
tensor([[0.0990, 0.2772, 0.0351],
        [0.0898, 0.1196, 0.0665]])
tensor([[ 9., 27.,  3.],
        [ 8., 11.,  6.]])
tensor([[1., 1., 1.],
        [0., 1., 0.]])
tensor([[0.0882, 0.6917, 0.0111],
        [0.0726, 0.1287, 0.0397]])


#### 2. Element wise Operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(f"Tensor a: \n{a}\nTensor b: \n{b}")

Tensor a: 
tensor([[0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832]])
Tensor b: 
tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423]])


In [ ]:
# addition
print(a + b)

# substraction
print(a + b)

# multiplication
print(a * b)

# division
print(a / b)

# mod
print(a % b)

# power
print(a ** b)

tensor([[0.8848, 0.8151, 1.5295],
        [0.9792, 1.4407, 0.9255]])
tensor([[0.8848, 0.8151, 1.5295],
        [0.9792, 1.4407, 0.9255]])
tensor([[0.1848, 0.0050, 0.5499],
        [0.0680, 0.4914, 0.1996]])
tensor([[1.6206, 0.0076, 1.6465],
        [0.0833, 1.5974, 1.7037]])
tensor([[0.2095, 0.0062, 0.3736],
        [0.0753, 0.3314, 0.2409]])
tensor([[0.8158, 0.0163, 0.9717],
        [0.0965, 0.9351, 0.8315]])


In [ ]:
c = torch.tensor([1,-2,3,-4,-5])

# absolute value
print(torch.abs(c))

# negetive
print(torch.neg(c))

tensor([1, 2, 3, 4, 5])
tensor([-1,  2, -3,  4,  5])


In [ ]:
d = torch.tensor([1.9,2.57,3.97,4.03,5.91])
print(d)

tensor([1.9000, 2.5700, 3.9700, 4.0300, 5.9100])


In [ ]:
# round
print(torch.round(d))

#ceil
print(torch.ceil(d))

#floor
print(torch.floor(d))

#clamp
print(torch.clamp(d, min=2, max=4))

tensor([2., 3., 4., 4., 6.])
tensor([2., 3., 4., 5., 6.])
tensor([1., 2., 3., 4., 5.])
tensor([2.0000, 2.5700, 3.9700, 4.0000, 4.0000])


#### 3. Reduction Operation

In [ ]:
e = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
print(e)

tensor([[6., 2., 7.],
        [9., 7., 3.],
        [3., 4., 3.]])


In [ ]:
# sum
print(torch.sum(e))

# sum along column
print(torch.sum(e,dim=0))

# sum along rows
print(torch.sum(e,dim=1))

# mean
print(torch.mean(e))

# median
print(torch.median(e))

# min
print(torch.min(e))

# max
print(torch.max(e))

# product
print(torch.prod(e))

# standard deviation
print(torch.std(e))

# variance
print(torch.var(e))

# argmax
print(torch.argmax(e))

# argmin
print(torch.argmin(e))

tensor(44.)
tensor([18., 13., 13.])
tensor([15., 19., 10.])
tensor(4.8889)
tensor(4.)
tensor(2.)
tensor(9.)
tensor(571536.)
tensor(2.4210)
tensor(5.8611)
tensor(3)
tensor(1)


#### 4. Matrix Operation

In [ ]:
mat_x = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
mat_y = torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)

In [ ]:
print(mat_x)

tensor([[7., 0., 9.],
        [0., 9., 6.]])


In [ ]:
print(mat_y)

tensor([[9., 5.],
        [4., 8.],
        [8., 6.]])


In [ ]:
# matrix multiplication

torch.matmul(mat_x, mat_y)

tensor([[135.,  89.],
        [ 84., 108.]])

In [ ]:
vec1=torch.tensor([4,6])
vec2=torch.tensor([3,5])

In [ ]:
# dot product
torch.dot(vec1,vec2)

tensor(42)

In [ ]:
# transpose

torch.transpose(mat_x,0,1)

tensor([[7., 0.],
        [0., 9.],
        [9., 6.]])

In [ ]:
mat_z=torch.randint(size=(3,3), low=5, high=100, dtype=torch.float32)

# determinant
torch.det(mat_z)

tensor(154335.)

In [ ]:
# inverse

torch.inverse(mat_z)

tensor([[ 0.0038, -0.0338,  0.0265],
        [ 0.0125,  0.0179, -0.0198],
        [-0.0069,  0.0340, -0.0123]])

#### 5. Comparision Operation

In [ ]:
i = torch.randint(size=(3,3), low=0, high=10)
j = torch.randint(size=(3,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 9, 4],
        [3, 8, 9],
        [3, 7, 8]])
tensor([[1, 4, 1],
        [6, 3, 2],
        [0, 9, 8]])


In [ ]:
## greater
print(i > j)

## less than
print(i < j)

## equal to
print(i == j)

## not equal to
print(i != j)

tensor([[ True,  True,  True],
        [False,  True,  True],
        [ True, False, False]])
tensor([[False, False, False],
        [ True, False, False],
        [False,  True, False]])
tensor([[False, False, False],
        [False, False, False],
        [False, False,  True]])
tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True, False]])


#### 6. Special Functions in PyTorch

In [ ]:
mat_a = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

print(mat_a)

tensor([[5., 3., 7.],
        [7., 5., 9.],
        [1., 5., 1.]])


In [ ]:
# log

torch.log(mat_a)

tensor([[1.6094, 1.0986, 1.9459],
        [1.9459, 1.6094, 2.1972],
        [0.0000, 1.6094, 0.0000]])

In [ ]:
# exp
torch.exp(mat_a)

tensor([[1.4841e+02, 2.0086e+01, 1.0966e+03],
        [1.0966e+03, 1.4841e+02, 8.1031e+03],
        [2.7183e+00, 1.4841e+02, 2.7183e+00]])

In [ ]:
# sqrt
torch.sqrt(mat_a)

tensor([[2.2361, 1.7321, 2.6458],
        [2.6458, 2.2361, 3.0000],
        [1.0000, 2.2361, 1.0000]])

In [ ]:
# sigmoid
torch.sigmoid(mat_a)

tensor([[0.9933, 0.9526, 0.9991],
        [0.9991, 0.9933, 0.9999],
        [0.7311, 0.9933, 0.7311]])

In [ ]:
# softmax

torch.softmax(mat_a, dim=1)

tensor([[0.1173, 0.0159, 0.8668],
        [0.1173, 0.0159, 0.8668],
        [0.0177, 0.9647, 0.0177]])

In [ ]:
# relu
torch.relu(mat_a)

tensor([[5., 3., 7.],
        [7., 5., 9.],
        [1., 5., 1.]])

#### 7. Inplace Operations

In [ ]:
## It will make changes inside a io_a variable
## Inplace operation helpful in memory allocation
# By using it we can replace or add a tensor variable with other tensor

io_a = torch.rand(2,3)
io_b = torch.rand(2,3)

print(io_a)
print(io_b)

tensor([[0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340]])
tensor([[0.1371, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])


In [ ]:
io_a.add_(io_b)

tensor([[0.4683, 0.8345, 0.1747],
        [0.2895, 0.8496, 0.4964]])

In [ ]:
io_a

tensor([[0.4683, 0.8345, 0.1747],
        [0.2895, 0.8496, 0.4964]])

In [ ]:
io_a.relu_()

tensor([[0.4683, 0.8345, 0.1747],
        [0.2895, 0.8496, 0.4964]])

#### 8. Copying a Tensor

In [ ]:
ct_a = torch.rand(2,3)
ct_b = ct_a

In [ ]:
ct_a

tensor([[0.1816, 0.9998, 0.5944],
        [0.6541, 0.0337, 0.1716]])

In [ ]:
## If we make changes ct_a it will reflect it in ct_b too, as it is a assignment operator

## Checking if any changes done in ct_a will reflect in ct_b

ct_a[0][0] = 0

ct_a

tensor([[0.0000, 0.9998, 0.5944],
        [0.6541, 0.0337, 0.1716]])

Changes made inside ct_b variable also.

In [ ]:
ct_b

tensor([[0.0000, 0.9998, 0.5944],
        [0.6541, 0.0337, 0.1716]])

In [ ]:
print(f"Memory Location ID, ct_a: {id(ct_a)}")
print(f"Memory Location ID, ct_b: {id(ct_b)}")

Memory Location ID, ct_a: 135585155712416
Memory Location ID, ct_b: 135585155712416


Which is same.

In [ ]:
## But if we use clone function it will create a copy with new memory location

ct_b = ct_a.clone()

print("Now again checking the Memory location ID.")
print(f"Memory Location ID, ct_a: {id(ct_a)}")
print(f"Memory Location ID, ct_b: {id(ct_b)}")

Now again checking the Memory location ID.
Memory Location ID, ct_a: 135585155712416
Memory Location ID, ct_b: 135585155734960


Which is different now, as the `clone()` function create a copy of other variable and If we make any changes inside a primary variable it will not reflect in secondary variable.

#### 9.Tensor Operation on GPU

In [ ]:
## Checking for the available GPU

torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [ ]:
## Creating a tensor inside a GPU

torch.rand(5,4, device=device)

tensor([[0.4778, 0.9731, 0.9599, 0.4291],
        [0.6058, 0.9870, 0.1361, 0.2313],
        [0.2064, 0.9041, 0.2367, 0.3105],
        [0.6701, 0.9356, 0.2972, 0.5078],
        [0.7745, 0.5049, 0.5190, 0.8688]], device='cuda:0')

In [ ]:
## Moving an existing tensor to GPU

new_tensor = torch.rand(5,4)
gpu_tensor = new_tensor.to(device) ## moving tensor to GPU with a new variable

print(gpu_tensor)

tensor([[0.9654, 0.5184, 0.7092, 0.0477],
        [0.5487, 0.9011, 0.0354, 0.6066],
        [0.6146, 0.1554, 0.7632, 0.6666],
        [0.2716, 0.6217, 0.7308, 0.8455],
        [0.7458, 0.3935, 0.4822, 0.6103]], device='cuda:0')


In [ ]:
## Defining a matrix multiplication and com-paring time of execution with GPU & CPU

import time

## defining a size of matrix
size = 10000 ## For large size perormance comparision

## Create a random matrices on CPU
mat_cpu1 = torch.randn(size,size)
mat_cpu2 = torch.randn(size,size)

#Measure time on CPU
start_time  = time.time()
mat_result_cpu = torch.matmul(mat_cpu1,mat_cpu1) ## Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time of CPU: {cpu_time:.4f} seconds")


## Moving matrices to GPU\
mat_gpu1 = mat_cpu1.to(device)
mat_gpu2 = mat_cpu2.to(device)

#Measure time on CPU
start_time  = time.time()
mat_result_gpu = torch.matmul(mat_gpu1,mat_gpu2) ## Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time of GPU: {gpu_time:.4f} seconds")
print(f"By {((cpu_time-gpu_time)/cpu_time)*100:.2f}% GPU is faster then CPU.")

Time of CPU: 18.0805 seconds
Time of GPU: 0.5661 seconds
By 96.87% GPU is faster then CPU.


#### 10. Reshaping the Tensor

In [ ]:
rt_a = torch.ones(4,4)
rt_a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
rt_a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
## Flatten
rt_a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# permute
rt_b = torch.rand(2,3,4)
rt_b

tensor([[[0.0596, 0.7384, 0.7772, 0.8373],
         [0.9050, 0.7960, 0.8753, 0.5520],
         [0.6834, 0.3949, 0.1126, 0.9893]],

        [[0.0532, 0.3011, 0.5797, 0.7637],
         [0.7055, 0.5970, 0.9134, 0.0620],
         [0.6421, 0.6997, 0.2970, 0.8148]]])

In [ ]:
# checking earlier shape
print(f"Shape before permute function: {rt_b.shape}")
rt_b = rt_b.permute(2,1,0)
print(f"Shape after permute function: {rt_b.shape}")

Shape before permute function: torch.Size([2, 3, 4])
Shape after permute function: torch.Size([4, 3, 2])


In [ ]:
# Unsqueeze
rt_c = torch.rand(226,226,3)
rt_c

tensor([[[0.3447, 0.8893, 0.4901],
         [0.5619, 0.6410, 0.0918],
         [0.6088, 0.1929, 0.3408],
         ...,
         [0.0276, 0.0370, 0.4829],
         [0.6519, 0.7610, 0.3605],
         [0.6434, 0.5843, 0.5556]],

        [[0.2469, 0.2151, 0.7112],
         [0.0511, 0.0339, 0.2075],
         [0.4363, 0.8252, 0.3148],
         ...,
         [0.7230, 0.0698, 0.3545],
         [0.5301, 0.6158, 0.8369],
         [0.4801, 0.9573, 0.2420]],

        [[0.9836, 0.2940, 0.2669],
         [0.8525, 0.1263, 0.0731],
         [0.3528, 0.0213, 0.4240],
         ...,
         [0.8280, 0.1918, 0.9571],
         [0.6199, 0.4212, 0.4252],
         [0.7608, 0.5398, 0.1655]],

        ...,

        [[0.7335, 0.1999, 0.7473],
         [0.1535, 0.6789, 0.5701],
         [0.6077, 0.2453, 0.6857],
         ...,
         [0.3255, 0.3830, 0.0053],
         [0.9447, 0.6550, 0.2973],
         [0.8045, 0.4373, 0.9749]],

        [[0.4834, 0.1764, 0.6903],
         [0.6803, 0.2422, 0.1910],
         [0.

In [ ]:
rt_c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze
rt_d = torch.rand(1,20)
rt_d # 2 dimensinal tensor

tensor([[0.8868, 0.2489, 0.3902, 0.5729, 0.5536, 0.2042, 0.3379, 0.9554, 0.7228,
         0.0415, 0.8932, 0.2918, 0.7903, 0.9663, 0.2115, 0.7699, 0.7393, 0.9764,
         0.6127, 0.8806]])

In [ ]:
rt_d.squeeze(0) # it will convert it to 1-dimensional tensor

tensor([0.8868, 0.2489, 0.3902, 0.5729, 0.5536, 0.2042, 0.3379, 0.9554, 0.7228,
        0.0415, 0.8932, 0.2918, 0.7903, 0.9663, 0.2115, 0.7699, 0.7393, 0.9764,
        0.6127, 0.8806])

#### 11. NumPy vs. PyTorch

In [ ]:
import numpy as np

## Creaing a tensor
t = torch.tensor([1,2,3,4,5])
t

tensor([1, 2, 3, 4, 5])

In [ ]:
# Coverting to numpy array
t_array = t.numpy()

In [ ]:
type(t_array)

numpy.ndarray

In [ ]:
# Creating a Numpy array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# Converting to tensor
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5])