In [23]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [24]:
sentences = [
    "The quick brown fox jumps over the lazy dog."
    "I love playing football with my friends."
    "The sun rises in the east and sets in the west."
    "Machine learning is a subset of artificial intelligence."
    "The cat purrs contentedly on my lap."
    "I am excited to try out this new restaurant tonight."
    "The capital of France is Paris."
    "The new iPhone is a game-changer."
    "I am learning to play the guitar in my free time."
    "The weather is beautiful today, isn't it?"
]

sentences_ = [sentence.lower() for sentence in sentences]
sentences_ = [sentence.split('.') for sentence in sentences_]
sentences_ = sentences_[0]
sentences_

['the quick brown fox jumps over the lazy dog',
 'i love playing football with my friends',
 'the sun rises in the east and sets in the west',
 'machine learning is a subset of artificial intelligence',
 'the cat purrs contentedly on my lap',
 'i am excited to try out this new restaurant tonight',
 'the capital of france is paris',
 'the new iphone is a game-changer',
 'i am learning to play the guitar in my free time',
 "the weather is beautiful today, isn't it?"]

In [25]:
## Defining vocabulary size
vocab_size = 10000

## One hot representation
one_hot_mat = [one_hot(words, vocab_size) for words in sentences_]
one_hot_mat

[[1981, 421, 5901, 9264, 2942, 1044, 1981, 8099, 2500],
 [3084, 4428, 3127, 3432, 2067, 9737, 3553],
 [1981, 8409, 277, 2377, 1981, 1826, 8976, 3754, 2377, 1981, 317],
 [6223, 9794, 1104, 8543, 9419, 9951, 9773, 5515],
 [1981, 962, 7529, 126, 2615, 9737, 5159],
 [3084, 4554, 9306, 3578, 4460, 2348, 9593, 8493, 4043, 2732],
 [1981, 1021, 9951, 3124, 1104, 1758],
 [1981, 8493, 6047, 1104, 8543, 1931, 3380],
 [3084, 4554, 9794, 3578, 3236, 1981, 8905, 2377, 9737, 7653, 2062],
 [1981, 3625, 1104, 6824, 652, 6402, 8106]]

In [26]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [27]:
## Finding the max length of the one hot encoded vectors
sent_len = max(len(i) for i in one_hot_mat)+1
print(f"Maximum length of the sentences: {sent_len}")

Maximum length of the sentences: 12


In [28]:
## Creating embedded vectors with padding
embedded_docs = pad_sequences(one_hot_mat,padding='pre',maxlen=sent_len)

print("Checking vector after padding:\n", embedded_docs)

Checking vector after padding:
 [[   0    0    0 1981  421 5901 9264 2942 1044 1981 8099 2500]
 [   0    0    0    0    0 3084 4428 3127 3432 2067 9737 3553]
 [   0 1981 8409  277 2377 1981 1826 8976 3754 2377 1981  317]
 [   0    0    0    0 6223 9794 1104 8543 9419 9951 9773 5515]
 [   0    0    0    0    0 1981  962 7529  126 2615 9737 5159]
 [   0    0 3084 4554 9306 3578 4460 2348 9593 8493 4043 2732]
 [   0    0    0    0    0    0 1981 1021 9951 3124 1104 1758]
 [   0    0    0    0    0 1981 8493 6047 1104 8543 1931 3380]
 [   0 3084 4554 9794 3578 3236 1981 8905 2377 9737 7653 2062]
 [   0    0    0    0    0 1981 3625 1104 6824  652 6402 8106]]


In [31]:
## Defining dimention to create embedding vector
dim = 10

## Creating the model
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_len))
model.compile('adam', 'mse')
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
predicted_arr = model.predict(embedded_docs)
display(predicted_arr)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[[ 1.51051916e-02, -3.76477614e-02, -1.66742206e-02, ...,
          1.26177110e-02, -1.30003802e-02,  1.39978416e-02],
        [ 1.51051916e-02, -3.76477614e-02, -1.66742206e-02, ...,
          1.26177110e-02, -1.30003802e-02,  1.39978416e-02],
        [ 1.51051916e-02, -3.76477614e-02, -1.66742206e-02, ...,
          1.26177110e-02, -1.30003802e-02,  1.39978416e-02],
        ...,
        [ 4.30870317e-02, -1.88988447e-02,  9.82481241e-03, ...,
         -4.79698069e-02, -4.26184312e-02, -4.86214869e-02],
        [ 7.84711912e-03,  9.84302908e-03,  6.72129542e-03, ...,
          4.24397029e-02,  7.98773021e-04, -3.23030576e-02],
        [ 2.38431618e-03,  4.48671840e-02,  3.17498781e-02, ...,
          2.62413360e-02,  1.15875006e-02, -1.29579529e-02]],

       [[ 1.51051916e-02, -3.76477614e-02, -1.66742206e-02, ...,
          1.26177110e-02, -1.30003802e-02,  1.39978416e-02],
        [ 1.51051916e-02, -3.76477614e-02, -1.66742206e-02, ...,
          1.26177110e-02, -1.30003802e

In [37]:
print("predicted_arr.shape:", predicted_arr.shape)
print("First sentence array:\n\n", predicted_arr[0][0])

predicted_arr.shape: (10, 12, 10)
First sentence array:

 [ 0.01510519 -0.03764776 -0.01667422  0.03280601  0.02979567  0.04352415
 -0.0035787   0.01261771 -0.01300038  0.01399784]
